service: binarySendGetApi
provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless
  region: ap-northeast-1
  memorySize: 128
  timeout: 3
  deploymentBucket:
    serverSideEncryption: AES256
functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: hello
          method: get
          integration: lambda
