service: simple

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless

  stage: ${opt:stage, 'dev'} # dev or production
  region: ap-northeast-1 # Overwrite the default region used. Default is us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 3

  environment:
    STAGE: ${self:provider.stage}
    MY_ENV: ${env:MY_ENV_${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: any
          cors: true

